### ISSUE TITLE
error 503 while installing

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [jekyll/jekyll-import#465]
so yes, im using linux 

firstly i tried with 'normal user' to install gem but it saw that doesnt have access to /var , okay, went to root account. but now while installing im getting this error : 
```
hacknorris@hacknorris:/mnt/c76d2dda-01ec-40e1-ab04-6a5f44ff242d/git/hacknorris-aka-penguin.github.io$ sudo gem install jekyll-import
[sudo] password for hacknorris:             
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.1-x64-unknown.gemspec.rz)
```
would someone came back to this project ? (im seeing that last commit was year ago...)

info bout system im running now (maybe it my OS fault only) -> https://termbin.com/ex05

**Comment by parkr** [comment]
Hm, x64-unknown seems wrong. RubyGems should request x64-linux. What versions on Ruby (`ruby --version`) and RubyGems (`gem --version`) are you using? I found https://github.com/sparklemotion/nokogiri/issues/2415 which looks pretty similar. The problem there was using an old Ruby version.

**Comment by parkr** [comment]
Also! If you don't get a response in an issue, you can always chat with the community here: https://talk.jekyllrb.com/

**Comment by hacknorris-aka-penguin** [comment]
k. version is : 
ruby -> `ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]`

gem -> `2.7.6.2`

how much old and unsupported?

**Comment by hacknorris-aka-penguin** [comment]
and these are updates i can do (from apt) : 

```
ruby2.5-dev/oldstable 2.5.5-3+deb10u4 amd64 [upgradable from: 2.5.5-3+deb10u3]
ruby2.5-doc/oldstable,oldstable 2.5.5-3+deb10u4 all [upgradable from: 2.5.5-3+deb10u3]
ruby2.5/oldstable 2.5.5-3+deb10u4 amd64 [upgradable from: 2.5.5-3+deb10u3]
```

**Comment by parkr** [comment]
Ruby 2.5 is EOL as of last March: https://www.ruby-lang.org/en/downloads/branches/

Could you use a different package repo? Maybe `stable`?

**Comment by hacknorris-aka-penguin** [comment]
i use apt. flatpak i should?

**Comment by hacknorris-aka-penguin** [comment]
reinstalled ruby. now not having gem : |

**Comment by hacknorris-aka-penguin** [comment]
and now question : 

how can i install gem both with ruby 3.1 on linux mint while apt have only ruby 2.5 (very outdated and unsupported) BOTH with gem but snap have ruby 3.1 without gem. gem is required to install cause originally is even in bundle with ruby (its installer, same as dpkg for linux). how i can force apt to install package **without** dependencies? cause ruby is installed 3.1 from snap (not 2.5 from apt, on other path)

only install from source?

**Comment by ashmaroli** [comment]
@hacknorris-aka-penguin The reason Nokogiri-1.13 failed to install on Ruby 2.5 earlier was because the minimum required Ruby version for Nokogiri-1.13 is 2.6.
Ruby 2.6 is on the verge of EOL at end of March this year.
That leaves Rubies 2.7, 3.0, 3.1.

I recommend using Ruby 2.7 until towards end of March next year.
Ruby 3.x is newer but not widely used yet.

However, if you would still like to install the latest release, you can try via various *version managers*, the most popular ones being `rbenv` and `rvm`. Using version managers, you can install multiple ruby versions easily on your *local user*, and easily switch across various installed Ruby versions in case of issues.

**Comment by hacknorris-aka-penguin** [comment]
means - installing from source? from git ? i dont like one-time install managers...

**Comment by hacknorris-aka-penguin** [comment]
anyways - already done. installed ruby from source.

**Comment by parkr** [comment]
Glad you figured it out! `gem` might be a different package called `rubygems`, or `ruby-gem`. I don't have much experience with Linux Mint. Installing from source is how many people do it. They use `rbenv` or `rvm` so you can reuse them for all your Ruby gems instead of being one-time. https://ubunlog.com/en/ruby-different-ways-to-install-it-on-ubuntu-20-04/

**Comment by hacknorris-aka-penguin** [comment]
naa. just installing gem from source worked. now fine;p
