### ISSUE TITLE
Please add dependencies to Importer docs

### ISSUE THREAD

**Issue by SimonDarksideJ** [jekyll/jekyll-import#467]
I'm new to Ruby and Jekyll, so I'm not as familiar with how importers and such work.

So if there are "Requirements" for an importer to work, PLEASE document them on the docs page and NOT just the run command.

Just spent a few hours trying to get the Ghost importer to run only to find:

1. I needed to also run "gem install jekyll-import"
2. Then it turns out I needed another gem and had to run "gem install sequel"
3. Then I needed sqlite3 -> "gem install sqlite3"

NEVER assume the reader / user has complete knowledge or expect them to know things, please just be clear with install instructions and usage to avoid confusion

After all that, the Ghost importer still didn't work as it appears "out of date" with Ghost 3 / 4 db schema.  Too much time wasted

**Comment by parkr** [comment]
@SimonDarksideJ Hello! I'm very sorry you lost time. Unfortunately these importers don't get a ton of love. Thank you for sharing your experience with us so that we can improve this for future users. @ashmaroli has a pull request in the works to add required libraries to the docs.

I'm not sure when our Ghost importer was written but I believe it was years ago. If you are willing to share your Ghost database so we can make improvements to support later versions of ghost, that would be appreciated!

**Comment by SimonDarksideJ** [comment]
[ghost.zip](https://github.com/jekyll/jekyll-import/files/8199682/ghost.zip)
Here you go, nothing sensitive in there.  But hope that helps improve the importer.

The link to the ghost.json importer is a good reference to ensure tags and other content such as feature images are supported too.
