### ISSUE TITLE
You must install the 'jekyll-import' gem version > 0 to use the 'jekyll import' command.

### ISSUE THREAD

**Issue by Kugeleis** [jekyll/jekyll-import#530]
After intalling the importer with `gem install jekyll-import` I get this error when running `jekyll import wordpressdotcom --source ./mysite.WordPress.xml`. What's wrong?

**Comment by Alexconquer** [comment]
Same problem

**Comment by dana-futa** [comment]
I'm have the same issue with tumblr.

**Comment by parkr** [comment]
Are you able to run the command as `jekyll-import ...` with the hyphen `-` between Jekyll and import?

**Comment by dana-futa** [comment]
When I do that I get this error: 'jekyll-import' is not recognized as an internal or external command, operable program or batch file.

I've tried uninstalling and reinstalling jekyll-import too.
```
gem uninstall jekyll-import
gem install jekyll-import
```

My jekyll-import version given from this command `gem list jekyll-import` is:
jekyll-import (0.22.0)

**Comment by Kugeleis** [comment]
I did `bundle install` after the gem install stuff and it worked. my gemfile has
````
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-import", "~>0.22"
  gem "hpricot"
  gem "open_uri_redirections"
end
```

**Comment by dana-futa** [comment]
Just tried the `bundle install` but it didn't change my gemfile. It added 3 files, each of type "File". One file called "false", one file called "true", and one file called "html". The false and true files don't have any content. The file named html only contains "Invalid drive specification."

I added `gem "jekyll-import", "~>0.22"` manually to my gemfile.
```
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-import", "~>0.22"
end
```
When I ran this command to get tumblr posts 
`jekyll import tumblr --url <tumblrUrlHere> --grab_images true --add_highlights true --rewrite_urls true`

I got this error: 
```
`block in rewrite_urls_and_redirects': undefined method `encode' for URI:Module (NoMethodError)

            tumblr_url = URI.parse(URI.encode(post[:slug])).path
```

Since the images are most important, I tried the command without the last two flags:
`jekyll import tumblr --url <tumblrUrlHere> --grab_images true`

I did get this deprecation warning, but it still seemed to work! "Deprecation: The 'url' setting can only be set in your config files."
