### ISSUE TITLE
HTML links

### ISSUE THREAD

**Issue by MartinThoma** [jekyll/jekyll-import#96]
The following Wordpress post content

    You can format time any way you like, just look at <a href="http://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior">this reference</a>.

was transformed to

    You can format time any way you like, just look at <a href="http:&#47;&#47;docs.python.org&#47;2&#47;library&#47;datetime.html#strftime-and-strptime-behavior">this reference<&#47;a>.

So `/` should not (or at least not always) be converted to `&#47;`.

**Comment by hfiguiere** [comment]
I have to set ```clean_entities``` to ```false``` for this to work.

**Comment by JustinLove** [comment]
Also saw this, as well as converting the / in `</p>` tags, causing them to break and get turned into `<&#47;p></p>` by the time all processing was done.

importers/wordpress.rb has `text.gsub!("/", "&#47;")` (currently line 349), but all the other entity fixups have the arguments flipped. Was that intentional?

Looking at it I may just leave clean off anyway, it looks like the gsubs could replace entities I had purposefully placed in the posts.
